
services:
  postgres:
    image: postgres:17
    container_name: inspectra
    restart: unless-stopped
    environment:
      POSTGRES_USER: aiarnob23
      POSTGRES_PASSWORD: aiarnob23
      POSTGRES_DB: inspectra
    ports:
      - "6667:5432" 
    volumes:
      - inspectra:/var/lib/postgresql/data
    networks:
      - inspectra

networks:
  inspectra:
    driver: bridge
    name: inspectra

volumes:
  inspectra:
    driver: local
    name: inspectra